version: '2'

services:
  web:
    build: ../
    privileged: true
    volumes:
      - ../:/var/www/bdd
    links:
      - mongo
    ports:
      - "8080:3030" 
    environment:    
      - ENVIRONMENT=docker
      - SUPORTE_MAIL
    container_name: rcpol_node    
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ../db:/data/db
    container_name: rcpol_mongo